name: Build Website

on:
  - workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v19
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build

      - name: Move app files
        run: mv /home/runner/work/fini8/fini8/dist/fini8 /home/runner/work/fini8/fini8/server

      - name: Upload build files
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: /home/runner/work/fini8/fini8/server

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: fininimini/website:latest
